package com.javacmap.shardingjdbcdemo.model;

import java.util.ArrayList;
import java.util.List;

public class OrderBaseInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public OrderBaseInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andSupplierUserIdIsNull() {
            addCriterion("supplier_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSupplierUserIdIsNotNull() {
            addCriterion("supplier_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierUserIdEqualTo(Long value) {
            addCriterion("supplier_user_id =", value, "supplierUserId");
            return (Criteria) this;
        }

        public Criteria andSupplierUserIdNotEqualTo(Long value) {
            addCriterion("supplier_user_id <>", value, "supplierUserId");
            return (Criteria) this;
        }

        public Criteria andSupplierUserIdGreaterThan(Long value) {
            addCriterion("supplier_user_id >", value, "supplierUserId");
            return (Criteria) this;
        }

        public Criteria andSupplierUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("supplier_user_id >=", value, "supplierUserId");
            return (Criteria) this;
        }

        public Criteria andSupplierUserIdLessThan(Long value) {
            addCriterion("supplier_user_id <", value, "supplierUserId");
            return (Criteria) this;
        }

        public Criteria andSupplierUserIdLessThanOrEqualTo(Long value) {
            addCriterion("supplier_user_id <=", value, "supplierUserId");
            return (Criteria) this;
        }

        public Criteria andSupplierUserIdIn(List<Long> values) {
            addCriterion("supplier_user_id in", values, "supplierUserId");
            return (Criteria) this;
        }

        public Criteria andSupplierUserIdNotIn(List<Long> values) {
            addCriterion("supplier_user_id not in", values, "supplierUserId");
            return (Criteria) this;
        }

        public Criteria andSupplierUserIdBetween(Long value1, Long value2) {
            addCriterion("supplier_user_id between", value1, value2, "supplierUserId");
            return (Criteria) this;
        }

        public Criteria andSupplierUserIdNotBetween(Long value1, Long value2) {
            addCriterion("supplier_user_id not between", value1, value2, "supplierUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdIsNull() {
            addCriterion("customer_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdIsNotNull() {
            addCriterion("customer_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdEqualTo(Long value) {
            addCriterion("customer_user_id =", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdNotEqualTo(Long value) {
            addCriterion("customer_user_id <>", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdGreaterThan(Long value) {
            addCriterion("customer_user_id >", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("customer_user_id >=", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdLessThan(Long value) {
            addCriterion("customer_user_id <", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdLessThanOrEqualTo(Long value) {
            addCriterion("customer_user_id <=", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdIn(List<Long> values) {
            addCriterion("customer_user_id in", values, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdNotIn(List<Long> values) {
            addCriterion("customer_user_id not in", values, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdBetween(Long value1, Long value2) {
            addCriterion("customer_user_id between", value1, value2, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdNotBetween(Long value1, Long value2) {
            addCriterion("customer_user_id not between", value1, value2, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTradeNoIsNull() {
            addCriterion("trade_no is null");
            return (Criteria) this;
        }

        public Criteria andTradeNoIsNotNull() {
            addCriterion("trade_no is not null");
            return (Criteria) this;
        }

        public Criteria andTradeNoEqualTo(String value) {
            addCriterion("trade_no =", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotEqualTo(String value) {
            addCriterion("trade_no <>", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoGreaterThan(String value) {
            addCriterion("trade_no >", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("trade_no >=", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLessThan(String value) {
            addCriterion("trade_no <", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLessThanOrEqualTo(String value) {
            addCriterion("trade_no <=", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLike(String value) {
            addCriterion("trade_no like", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotLike(String value) {
            addCriterion("trade_no not like", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoIn(List<String> values) {
            addCriterion("trade_no in", values, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotIn(List<String> values) {
            addCriterion("trade_no not in", values, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoBetween(String value1, String value2) {
            addCriterion("trade_no between", value1, value2, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotBetween(String value1, String value2) {
            addCriterion("trade_no not between", value1, value2, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andCreateTimeStampIsNull() {
            addCriterion("create_time_stamp is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeStampIsNotNull() {
            addCriterion("create_time_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeStampEqualTo(Long value) {
            addCriterion("create_time_stamp =", value, "createTimeStamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimeStampNotEqualTo(Long value) {
            addCriterion("create_time_stamp <>", value, "createTimeStamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimeStampGreaterThan(Long value) {
            addCriterion("create_time_stamp >", value, "createTimeStamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimeStampGreaterThanOrEqualTo(Long value) {
            addCriterion("create_time_stamp >=", value, "createTimeStamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimeStampLessThan(Long value) {
            addCriterion("create_time_stamp <", value, "createTimeStamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimeStampLessThanOrEqualTo(Long value) {
            addCriterion("create_time_stamp <=", value, "createTimeStamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimeStampIn(List<Long> values) {
            addCriterion("create_time_stamp in", values, "createTimeStamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimeStampNotIn(List<Long> values) {
            addCriterion("create_time_stamp not in", values, "createTimeStamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimeStampBetween(Long value1, Long value2) {
            addCriterion("create_time_stamp between", value1, value2, "createTimeStamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimeStampNotBetween(Long value1, Long value2) {
            addCriterion("create_time_stamp not between", value1, value2, "createTimeStamp");
            return (Criteria) this;
        }

        public Criteria andModifyTimeStampIsNull() {
            addCriterion("modify_time_stamp is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeStampIsNotNull() {
            addCriterion("modify_time_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeStampEqualTo(Long value) {
            addCriterion("modify_time_stamp =", value, "modifyTimeStamp");
            return (Criteria) this;
        }

        public Criteria andModifyTimeStampNotEqualTo(Long value) {
            addCriterion("modify_time_stamp <>", value, "modifyTimeStamp");
            return (Criteria) this;
        }

        public Criteria andModifyTimeStampGreaterThan(Long value) {
            addCriterion("modify_time_stamp >", value, "modifyTimeStamp");
            return (Criteria) this;
        }

        public Criteria andModifyTimeStampGreaterThanOrEqualTo(Long value) {
            addCriterion("modify_time_stamp >=", value, "modifyTimeStamp");
            return (Criteria) this;
        }

        public Criteria andModifyTimeStampLessThan(Long value) {
            addCriterion("modify_time_stamp <", value, "modifyTimeStamp");
            return (Criteria) this;
        }

        public Criteria andModifyTimeStampLessThanOrEqualTo(Long value) {
            addCriterion("modify_time_stamp <=", value, "modifyTimeStamp");
            return (Criteria) this;
        }

        public Criteria andModifyTimeStampIn(List<Long> values) {
            addCriterion("modify_time_stamp in", values, "modifyTimeStamp");
            return (Criteria) this;
        }

        public Criteria andModifyTimeStampNotIn(List<Long> values) {
            addCriterion("modify_time_stamp not in", values, "modifyTimeStamp");
            return (Criteria) this;
        }

        public Criteria andModifyTimeStampBetween(Long value1, Long value2) {
            addCriterion("modify_time_stamp between", value1, value2, "modifyTimeStamp");
            return (Criteria) this;
        }

        public Criteria andModifyTimeStampNotBetween(Long value1, Long value2) {
            addCriterion("modify_time_stamp not between", value1, value2, "modifyTimeStamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order_base_info
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 09 14:02:13 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}