package com.javacmap.shardingjdbcdemo.model;

import lombok.ToString;

@ToString
public class OrderBaseInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_base_info.order_id
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_base_info.supplier_user_id
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    private Long supplierUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_base_info.customer_user_id
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    private Long customerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_base_info.status
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_base_info.trade_no
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_base_info.create_time_stamp
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    private Long createTimeStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_base_info.modify_time_stamp
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    private Long modifyTimeStamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_base_info.order_id
     *
     * @return the value of t_order_base_info.order_id
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_base_info.order_id
     *
     * @param orderId the value for t_order_base_info.order_id
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_base_info.supplier_user_id
     *
     * @return the value of t_order_base_info.supplier_user_id
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public Long getSupplierUserId() {
        return supplierUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_base_info.supplier_user_id
     *
     * @param supplierUserId the value for t_order_base_info.supplier_user_id
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public void setSupplierUserId(Long supplierUserId) {
        this.supplierUserId = supplierUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_base_info.customer_user_id
     *
     * @return the value of t_order_base_info.customer_user_id
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public Long getCustomerUserId() {
        return customerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_base_info.customer_user_id
     *
     * @param customerUserId the value for t_order_base_info.customer_user_id
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public void setCustomerUserId(Long customerUserId) {
        this.customerUserId = customerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_base_info.status
     *
     * @return the value of t_order_base_info.status
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_base_info.status
     *
     * @param status the value for t_order_base_info.status
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_base_info.trade_no
     *
     * @return the value of t_order_base_info.trade_no
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_base_info.trade_no
     *
     * @param tradeNo the value for t_order_base_info.trade_no
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_base_info.create_time_stamp
     *
     * @return the value of t_order_base_info.create_time_stamp
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public Long getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_base_info.create_time_stamp
     *
     * @param createTimeStamp the value for t_order_base_info.create_time_stamp
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public void setCreateTimeStamp(Long createTimeStamp) {
        this.createTimeStamp = createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_base_info.modify_time_stamp
     *
     * @return the value of t_order_base_info.modify_time_stamp
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public Long getModifyTimeStamp() {
        return modifyTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_base_info.modify_time_stamp
     *
     * @param modifyTimeStamp the value for t_order_base_info.modify_time_stamp
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    public void setModifyTimeStamp(Long modifyTimeStamp) {
        this.modifyTimeStamp = modifyTimeStamp;
    }
}