# redis配置
spring:
  cache:
    type: redis
  redis:
    host: 192.168.3.144
    lettuce:
      pool:
        max-active: 16
        max-wait: 10ms

# 日志配置
logging:
  level:
    com:
      javacamp: debug