package com.javacmap.shardingjdbcdemo.dao;

import com.javacmap.shardingjdbcdemo.model.OrderBaseInfo;
import com.javacmap.shardingjdbcdemo.model.OrderBaseInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    long countByExample(OrderBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    int deleteByExample(OrderBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    int insert(OrderBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    int insertSelective(OrderBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    List<OrderBaseInfo> selectByExample(OrderBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    OrderBaseInfo selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrderBaseInfo record, @Param("example") OrderBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    int updateByExample(@Param("record") OrderBaseInfo record, @Param("example") OrderBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    int updateByPrimaryKeySelective(OrderBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_base_info
     *
     * @mbg.generated Wed Dec 09 14:02:13 CST 2020
     */
    int updateByPrimaryKey(OrderBaseInfo record);
}